import { test, expect } from '@playwright/test'

test('desktop public market and seller workspace', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Fresco en el mercado' })).toBeVisible()
  await page.screenshot({ path: 'test-results/desktop-board.png', fullPage: true })
  await page.getByLabel('Vista del prototipo').selectOption('operator')
  await expect(page.getByRole('heading', { name: /Productos y precios/ })).toBeVisible()
  await page.screenshot({ path: 'test-results/desktop-market.png', fullPage: false })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

for (const role of ['operator', 'producer']) {
  test(`${role}: mobile edits only the selected combination and keeps scroll position`, async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto(role === 'operator' ? '/operador/mercado' : '/productor/mercado')
    await expect(page.getByRole('navigation', { name: 'Navegación móvil' })).toBeVisible()
    await page.screenshot({ path: `test-results/mobile-${role}-market.png`, fullPage: false })
    const row = page.locator('.actor-product-price-list > span').first()
    const sibling = page.locator('.actor-product-price-list > span').nth(1)
    const siblingText = await sibling.innerText()
    const originalLabel = await row.locator(':scope > small').innerText()
    await row.getByRole('button', { name: /Cambiar precio/ }).click()
    const scrollY = await page.evaluate(() => scrollY)
    await expect(page.getByRole('dialog', { name: 'Cambiar precio', exact: true })).toBeVisible()
    await page.getByLabel('Nuevo precio').fill('123')
    await page.screenshot({ path: `test-results/mobile-${role}-editor.png`, fullPage: false })
    await page.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(row.locator('.actor-variant-price b')).toHaveText('$123')
    await expect(row.locator(':scope > small')).toHaveText(originalLabel)
    expect(await sibling.innerText()).toBe(siblingText)
    await expect(page.getByRole('status')).toContainText('actualizado a $123')
    expect(Math.abs((await page.evaluate(() => window.scrollY)) - scrollY)).toBeLessThan(5)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('invalid prices, immediate Escape cancellation and full combination editor', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/operador/mercado')
  const row = page.locator('.actor-product-price-list > span').first()
  const before = await row.locator('.actor-variant-price b').innerText()
  await row.getByRole('button', { name: /Cambiar precio/ }).click()
  await page.getByLabel('Nuevo precio').fill('0')
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('mayor a 0')
  await page.getByLabel('Nuevo precio').fill('79')
  await page.keyboard.press('Escape')
  await expect(row.locator('.actor-variant-price b')).toHaveText(before)
  await row.getByRole('button', { name: /Cambiar precio/ }).click()
  await page.getByLabel('Nuevo precio').fill('79')
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await row.getByRole('button', { name: /Editar combinación/ }).click()
  await page.getByLabel('Precio', { exact: true }).fill('79')
  await expect(page.getByLabel('Especie', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Precio', { exact: true })).toHaveValue('79')
  for (const label of ['Variedad', 'Unidad de medida', 'Presentación', 'Calibre', 'Categoría']) await expect(page.getByLabel(label, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row.locator('.actor-variant-price b')).toHaveText('$79')
})

test('search, filters, favorites, creation and narrow layouts', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 })
  await page.goto('/')
  await page.getByLabel('Buscar un producto').fill('Manzana')
  await expect(page.locator('.board-product-grid > article')).toHaveCount(1)
  await page.getByRole('button', { name: 'Agregar Manzana Fuji a favoritos' }).click()
  await expect(page.getByRole('button', { name: 'Quitar Manzana Fuji de favoritos' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpiar búsqueda', exact: true }).click()
  await page.getByRole('button', { name: 'Favoritos', exact: true }).click()
  await expect(page.locator('.board-product-grid > article')).toHaveCount(1)
  await page.getByRole('navigation', { name: 'Navegación móvil' }).getByRole('button', { name: 'Mi mercado' }).click()
  await page.getByRole('button', { name: 'Agregar publicación', exact: true }).click()
  await page.getByLabel('Especie', { exact: true }).selectOption('1')
  await page.getByLabel('Precio', { exact: true }).fill('68')
  await page.getByRole('button', { name: /Publicar combinación|Guardar cambios/ }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  for (const width of [320, 360, 390, 768, 1024]) {
    await page.setViewportSize({ width, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), { message: `No horizontal overflow at ${width}px` }).toBe(true)
  }
})
