import { test, expect, type Page } from '@playwright/test'

test.use({ viewport: { width: 390, height: 844 }, hasTouch: true })
const selectVersion = (page: Page, name: string) => page.getByRole('button', { name, exact: true }).click()
const priceOf = async (row: ReturnType<Page['locator']>) => Number((await row.locator('.actor-variant-price b').innerText()).replace('$', ''))

test('V1 has manual price editing and pencil; global selector preserves the screen and remembers the version', async ({ page }) => {
  await page.goto('/operador/mercado')
  const edit = page.getByRole('button', { name: /Editar combinación/ }).first()
  await expect(edit).toHaveText('')
  await expect(edit.locator('svg')).toBeVisible()
  await page.getByRole('textbox', { name: 'Buscar producto' }).fill('Manzana')
  await selectVersion(page, 'V2')
  await expect(page.getByRole('textbox', { name: 'Buscar producto' })).toHaveValue('Manzana')
  await expect(page).toHaveURL(/operador\/mercado$/)
  await page.reload()
  await expect(page.getByRole('button', { name: 'V2', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.price-stepper').first()).toBeVisible()
  await selectVersion(page, 'V1')
  await expect(page.locator('.price-stepper')).toHaveCount(0)
})

for (const actor of ['operador', 'productor']) {
  test(`${actor}: tap price to type in every variant; compact rows keep full-width labels and photos after price controls`, async ({ page }) => {
    await page.goto(`/${actor}/mercado`)
    for (const [index, version] of ['V1', 'V2', 'V3'].entries()) {
      await selectVersion(page, version)
      const row = page.locator('.actor-product-price-list > span').filter({ has: page.locator('.variant-photo-action') }).first()
      await row.getByRole('button', { name: /Cambiar precio/ }).tap()
      const dialog = page.getByRole('dialog', { name: 'Cambiar precio', exact: true })
      await expect(page.getByLabel('Nuevo precio')).toBeFocused()
      await expect(dialog.locator('input')).toHaveCount(1)
      await expect(dialog.locator('img, select, .combination-tags')).toHaveCount(0)
      await expect(dialog.getByRole('button')).toHaveCount(2)
      await dialog.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
      const dialogBox = await dialog.boundingBox()
      expect(Math.abs(dialogBox!.x + dialogBox!.width / 2 - 195)).toBeLessThan(2)
      expect(Math.abs(dialogBox!.y + dialogBox!.height / 2 - 422)).toBeLessThan(2)
      await page.getByLabel('Nuevo precio').fill(String(123 + index))
      await page.getByRole('button', { name: 'Confirmar', exact: true }).click()
      await expect(page.getByRole('dialog')).toHaveCount(0)
      await expect(row.locator('b')).toHaveText(`$${123 + index}`)
      await row.getByRole('button', { name: /Editar combinación/ }).tap()
      await expect(page.getByRole('dialog').getByLabel('Especie', { exact: true })).toBeVisible()
      await expect(page.getByRole('dialog').getByLabel('Variedad', { exact: true })).toBeVisible()
      await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
      const rowBox = await row.boundingBox(), labelBox = await row.locator(':scope > small').boundingBox()
      expect(labelBox!.width).toBeCloseTo(rowBox!.width, 0)
      expect(rowBox!.height).toBeLessThan(85)
      const lastControl = row.locator(version === 'V2' ? '.price-step-button' : version === 'V3' ? '.price-slider-trigger' : '.price-manual-trigger').last()
      const controlBox = await lastControl.boundingBox(), photoBox = await row.locator('.variant-photo-action').boundingBox()
      expect(photoBox!.x).toBeGreaterThanOrEqual(controlBox!.x + controlBox!.width)
      expect(Math.abs(photoBox!.y - controlBox!.y)).toBeLessThan(4)
      if (version === 'V3') {
        const pill = await row.locator('.price-slider-control').boundingBox()
        const amount = await row.locator('b').boundingBox()
        expect(amount!.x).toBeGreaterThanOrEqual(pill!.x)
        expect(amount!.x + amount!.width).toBeLessThan(pill!.x + pill!.width)
      }
    }
  })

  test(`V2 ${actor}: − / price / + changes exactly $10 and preserves sibling rows across versions`, async ({ page }) => {
    await page.goto(`/${actor}/mercado`)
    await selectVersion(page, 'V2')
    const row = page.locator('.actor-product-price-list > span').first()
    const sibling = page.locator('.actor-product-price-list > span').nth(1)
    const initial = await priceOf(row), siblingPrice = await priceOf(sibling)
    const label = await row.locator(':scope > small').innerText()
    const plus = row.getByRole('button', { name: /Aumentar/ }), minus = row.getByRole('button', { name: /Restar/ })
    await plus.scrollIntoViewIfNeeded()
    const plusBox = await plus.boundingBox(), priceBox = await row.locator('b').boundingBox(), minusBox = await minus.boundingBox()
    expect(minusBox!.x + minusBox!.width).toBeLessThanOrEqual(priceBox!.x + 1)
    expect(plusBox!.x).toBeGreaterThanOrEqual(priceBox!.x + priceBox!.width - 1)
    for (let count = 1; count <= 3; count++) { await plus.click(); await expect(row.locator('b')).toHaveText(`$${initial + count * 10}`) }
    await minus.click()
    expect(await priceOf(row)).toBe(initial + 20)
    expect(await priceOf(sibling)).toBe(siblingPrice)
    await expect(row.locator(':scope > small')).toHaveText(label)
    await selectVersion(page, 'V1')
    expect(await priceOf(row)).toBe(initial + 20)
    await expect(row.locator('.price-stepper')).toHaveCount(0)
    await selectVersion(page, 'V3')
    expect(await priceOf(row)).toBe(initial + 20)
    await expect(row.getByRole('button', { name: /Deslizar precio/ })).toBeVisible()
  })

  test(`V3 ${actor}: touch drag changes draft only; double tap saves and restores list position`, async ({ page }) => {
    await page.goto(`/${actor}/mercado`)
    await selectVersion(page, 'V3')
    const row = page.locator('.actor-product-price-list > span').nth(4)
    const sibling = page.locator('.actor-product-price-list > span').nth(3)
    const initial = await priceOf(row), neighbor = await priceOf(sibling)
    await row.getByRole('button', { name: /Deslizar precio/ }).click()
    await page.getByRole('dialog').evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
    const scroll = await page.evaluate(() => window.scrollY)
    const slider = page.getByRole('slider')
    const bounds = await slider.boundingBox()
    const dialog = await page.getByRole('dialog').boundingBox()
    expect(dialog!.y).toBe(0)
    expect(dialog!.height).toBe(844)
    const x = Math.round(bounds!.x + bounds!.width / 2), y = Math.round(bounds!.y + bounds!.height / 2)
    const session = await page.context().newCDPSession(page)
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y: y - 100 }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(slider).toHaveAttribute('aria-valuenow', String(initial + 20))
    expect(await priceOf(row)).toBe(initial)
    // A drag release and a single tap must never be treated as a confirmation.
    await page.touchscreen.tap(x, y)
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.touchscreen.tap(x, y)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    expect(await priceOf(row)).toBe(initial + 20)
    expect(await priceOf(sibling)).toBe(neighbor)
    expect(Math.abs((await page.evaluate(() => window.scrollY)) - scroll)).toBeLessThan(5)
  })
}

test('V2 rejects fractional prices and prevents subtracting into zero or negative prices', async ({ page }) => {
  await page.goto('/operador/mercado')
  const row = page.locator('.actor-product-price-list > span').first()
  await row.getByRole('button', { name: /Cambiar precio/ }).click()
  await page.getByLabel('Nuevo precio').fill('10,25')
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('entero')
  await page.getByLabel('Nuevo precio').fill('11')
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await selectVersion(page, 'V2')
  await row.getByRole('button', { name: /Restar/ }).click()
  await expect(row.locator('b')).toHaveText('$1')
  await expect(row.getByRole('button', { name: /Restar/ })).toBeDisabled()
  await row.getByRole('button', { name: /Aumentar/ }).click()
  await expect(row.locator('b')).toHaveText('$11')
})

test('V3 downward drag, keyboard, immediate cancellation, and read-only public views', async ({ page }) => {
  await page.goto('/operador/mercado')
  await selectVersion(page, 'V3')
  const row = page.locator('.actor-product-price-list > span').first()
  const initial = await priceOf(row)
  await row.getByRole('button', { name: /Deslizar precio/ }).click()
  const slider = page.getByRole('slider'), box = await slider.boundingBox()
  const x = box!.x + box!.width / 2, y = box!.y + box!.height / 2
  await page.mouse.move(x, y)
  await page.mouse.down()
  await page.mouse.move(x, y + 50, { steps: 5 })
  await page.mouse.up()
  await expect(slider).toHaveAttribute('aria-valuenow', String(initial - 10))
  await slider.press('ArrowUp')
  await expect(slider).toHaveAttribute('aria-valuenow', String(initial - 9))
  await page.keyboard.press('Escape')
  expect(await priceOf(row)).toBe(initial)
  await page.goto('/operadores/frutas-del-norte')
  await expect(page.locator('.price-slider-trigger')).toHaveCount(0)
  await selectVersion(page, 'V2')
  await expect(page.locator('.price-stepper')).toHaveCount(0)
})

test('all variants fit small screens and desktop', async ({ page }) => {
  await page.goto('/productor/mercado')
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    for (const version of ['V1', 'V2', 'V3']) {
      await selectVersion(page, version)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${version} at ${width}px`).toBe(true)
    }
  }
})
