name: CD - Deploy Prototipo UI

on:
  push:
    branches:
      - main
    paths:
      - 'proto-ui/**'
      - '.github/workflows/deploy-proto-ui.yml'

jobs:
  deploy-proto-ui:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Desplegar prototipo UI
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/proto-ui
          dockerfilePath: Dockerfile
          registryUrl: uamgrupo10acr.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: uam-prototipo-ui
          resourceGroup: Proyecto-PIS-2026